package main

import (
	"testing"
)

func TestSimpleMap(t *testing.T) {
	input := `..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........
`
	expected := `..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........
`

	output, _ := Solve(input)
	if output != expected {
		t.Errorf("For input '%s', expected '%s' but got '%s'", input, expected, output)
	}
}

func TestTripleSimpleMap(t *testing.T) {
	input := `..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
..........
`
	expected := `..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
..........
`
	output, _ := Solve(input)
	if output != expected {
		t.Errorf("For input '%s', expected '%s' but got '%s'", input, expected, output)
	}
}

func TestComplexMap(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`
	expected := `......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....A.....
...#........
#......#....
........A...
.........A..
..........#.
..........#.
`
	output, _ := Solve(input)
	if output != expected {
		t.Errorf("For input '%s', expected '%s' but got '%s'", input, expected, output)
	}
}
